version: '3'

services:
  web: &web
    environment:
      - DB_NAME=todo_app_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5433
      - DJANGO_SETTINGS_MODULE=main.settings.dev
    build: .
    volumes:
      - .:/code
    ports:
      - "8765:8765"
    restart: "always"
    depends_on:
      - db
      - mq
      - wk
  db:
    image: postgres
    environment:
      - POSTGRES_DB=todo_app_db
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432
    restart: "always"
  # rabbit message queue
  mq:
    image: gonkulatorlabs/rabbitmq # rabbitmq:3.7.14-alpine
    restart: "always"
  # celery worker service
  wk:
    <<: *web
    command: bash -c "celery -A main.todo worker -l info && celery -A main.todo beat -l info"
    ports: []
    depends_on: 
      - mq
      - db